# NUMPY DATATYPES:

In [4]:
import numpy as np

In [10]:
arr = np.array([1,2,3,4],dtype = 'f')

print(arr)
print(arr.dtype)

[1. 2. 3. 4.]
float32


In [12]:
#integer
arr = np.array([1.2,3.2,4.5,6.3,4.89],dtype = 'i')
print(arr)
print(arr.dtype)

[1 3 4 6 4]
int32


In [14]:
# changing datatype from float to int by using 'i' as a parameter value:
arr = np.array([1.2,3.2,4.5,6.3,4.89],dtype = 'i')
new = arr.astype('i')
print(new)
print(new.dtype)

[1 3 4 6 4]
int32


In [18]:
# change datatype from integer to boolean:

In [24]:
arr = np.array([4,0,5,6,-3,6,98,0,32,72])
new = arr.astype(bool)
print(new)
print(new.dtype)

[ True False  True  True  True  True  True False  True  True]
bool


# copy method : imp***

In [29]:
arr = np.array([7,8,24,36,45,56])
x = arr.copy()
arr[2]=28
print(arr)
print(x)

[ 7  8 28 36 45 56]
[ 7  8 24 36 45 56]


# view method :

In [32]:
arr = np.array([12,32,43,34,56])
x = arr.view()
arr[-2] = 24
print(arr)
print(x)

[12 32 43 24 56]
[12 32 43 24 56]


# RESHAPING ARRAYS:
Reshaping arrays means changing the structure or dimensions of an array (like rows and columns) without altering its data. For example, in Python with NumPy, you can turn a flat list of numbers into a grid, like rearranging 12 items into 3 rows of 4. It’s like reorganizing a pile of blocks into a new shape while keeping the same blocks.

In [39]:
#Convert the following 1-0 array with 12 elements into a 2D array. 
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]) 

In [45]:
print(arr.size)
newarr = arr.reshape(3,4)
print(newarr)

12
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [49]:
#Convert the following 1-0 array with 12 elements into a 3D array. 
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]) 

In [53]:
print(arr.size)
newarr = arr.reshape(2,2,3) #(shape,row,column)
print(newarr)

12
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


# Sorting Array:
Sorting arrays in Python means arranging a list of items (like numbers or words) in a specific order, like smallest to largest. Python makes it easy with the .sort() method for lists or the sorted() function, which can work on any iterable and give you a new sorted list. For example, [3, 1, 2].sort() turns into [1, 2, 3].

In [57]:
arr = np.array([2,45,63,45,86,45,76])
print(np.sort(arr))

[ 2 45 45 45 63 76 86]


In [62]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [64]:
#ADDITION OF TWO RAYS:
print(np.add(x,y))

[[ 6  8]
 [10 12]]


In [68]:
#SUBTRACTION OF THE ELEMENTS:
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]


In [74]:
# MULTIPLICATION OR PRODUCT:
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]


In [80]:
# DIVISION:
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [92]:
#sqare root:
print(np.sqrt(x))
print(np.sqrt(y))

[[1.         1.41421356]
 [1.73205081 2.        ]]
[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


# SLICING ARRAYS:

In [101]:
#SLice elements from index 1 to index 5 from the following array: 
arr=np.array([1, 2, 3, 4, 5, 6, 7]) 
print(arr[1:12]) 

[2 3 4 5 6 7]


In [105]:
#SLice elements from index 4 to the end of the array: 
arr=np.array([1, 2, 3, 4, 5, 6, 7]) 
print(arr[4:]) 

[5 6 7]


In [111]:
#SLice elements from the beginning to index 4 (not included): 
arr=np.array([1, 2, 3, 4, 5, 6, 7]) 
print(arr[:6]) 

[1 2 3 4 5 6]


# NEGATIVE SLICING:

In [116]:
#SLice from the index 3 from the end to index 1 from the end: 
arr=np.array([1, 2, 3, 4, 5, 6, 7]) 
print(arr[-3:-1]) 

[5 6]


In [130]:
#Use the step value to determine the step of the slicing: 
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 4, 1, 5,3,6,2,7,21]) 
print(arr[0:13:2]) #step is apply Like step-1 


[1 3 5 7 9 1 3]


In [142]:
#Return every other element from the entire array: 
arr=np.array([1, 2, 3, 4, 5, 6, 7]) 
print(arr[::3]) 
[147] 

[1 4 7]


[147]

In [158]:
#Slicing 2-D Arrays 
#From the second element, slice elements from index 1 to index 4 (not included): 
arr=np.array([[1, 2, 3, 4, 5],
             [1, 2, 32, 14, 5], 
             [1, 4, 3, 34, 51],
             [6, 7, 8, 49, 10]]) 
print(arr[2, 1:3]) 

[4 3]


In [166]:
#return both element index 3 
arr=np.array([[1, 2, 3, 4, 5], #0 
              [6, 7, 8, 9, 10], #1
              [6, 7, 8, 9, 10], #2 ID 
              [6, 7, 8, 9, 10]]) #3 1D 
print(arr[0:8, 1]) #(10, element) 

[2 7 7 7]


In [170]:
t=np.array([[2,4,6,2], #0 
            [5,7,2,8], #1 
            [9,4,2,4]]) #2  
print(t[0:4,2]) 

[6 2 2]


In [182]:
t=np.array([[2,4,6,2], #0 
            [5,7,2,8], #1 
            [9,4,2,4]]) #2 
print(t[0:2, 0:3))

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (3811416494.py, line 4)

In [ ]:
t 
np.array([[2,4,6,2), #0 
[5,7,2,8), #1 
[9,4,2,4]]) #2 
[19]: 
print(t[0:4,2]) 
[622] 
[34]: t 
np.array([[2,4,6,2], #0 
[5,7,2,8), #1 
[9,4,2,4]]) #2 
print(t[0:2, 0:31) 